INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Kasper','Idaho',                     ubicado_en (ubicacion( 'Iran, Islamic Republic of',399849974 )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Uriah','California',                 ubicado_en (ubicacion( 'Moldova',525371982                   )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Shay','New Mexico',                  ubicado_en (ubicacion( 'Iceland',3839482                     )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Melyssa','Texas',                    ubicado_en (ubicacion( 'Ethiopia',25626062                   )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Christopher','Indiana',              ubicado_en (ubicacion( 'Philippines',866910123               )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tanek','Connecticut',                ubicado_en (ubicacion( 'Antigua and Barbuda',667655479       )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Amena','Maine',                      ubicado_en (ubicacion( 'Mexico',729172638                    )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Fleur','District of Columbia',       ubicado_en (ubicacion( 'Gibraltar',232138627                 )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Wayne','Wisconsin',                  ubicado_en (ubicacion( 'Kyrgyzstan',730970384                )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Lacy','Kansas',                      ubicado_en (ubicacion( 'Martinique',820205979                )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Mona','Texas',                       ubicado_en (ubicacion( 'Egypt',318616770                     )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Isadora','Illinois',                 ubicado_en (ubicacion( 'Dominica',513021936                  )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ashton','Wyoming',                   ubicado_en (ubicacion('Guadeloupe',222430086              )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Gillian','Wyoming',                  ubicado_en (ubicacion('Ireland',424726400                   )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Leslie','Connecticut',               ubicado_en (ubicacion('Denmark',348037787                                                   )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Maris','Colorado',                   ubicado_en (ubicacion('Israel',920586949                                                        )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Aurelia','Virginia',                 ubicado_en (ubicacion('Faroe Islands',224303776                                               )));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Violet','Nevada',                    ubicado_en (ubicacion('Trinidad and Tobago',56155244)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Karly','Wyoming',                    ubicado_en (ubicacion('Aruba',2070838)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('George','Michigan',                  ubicado_en (ubicacion('South Africa',919138314)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Madeson','Tennessee',                ubicado_en (ubicacion('Zimbabwe',286805573)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Maite','Georgia',                    ubicado_en (ubicacion('Algeria',283222471)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Jayme','Nevada',                     ubicado_en (ubicacion('Liberia',403367048)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Adrian','New Hampshire',             ubicado_en (ubicacion('Sri Lanka',452114313)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Vaughan','Louisiana',                ubicado_en (ubicacion('Suriname',827360610)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Clementine','New Hampshire',         ubicado_en (ubicacion('Suriname',548789884)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Lavinia','Rhode Island',             ubicado_en (ubicacion('Sri Lanka',492719310)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Colorado','Indiana',                 ubicado_en (ubicacion('Equatorial Guinea',889334300)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Iona','New Jersey',                  ubicado_en (ubicacion('Afghanistan',737473193)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Sharon','Maryland',                  ubicado_en (ubicacion('Sri Lanka',830862925)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ursa','Washington',                  ubicado_en (ubicacion('Bahamas',907949720)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Kareem','Florida',                   ubicado_en (ubicacion('Uzbekistan',48079847)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Marah','North Dakota',               ubicado_en (ubicacion('Antarctica',293144886)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Abra','Wisconsin',                   ubicado_en (ubicacion('Cocos (Keeling) Islands',247947101)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tarik','Washington',                 ubicado_en (ubicacion('Spain',515111855)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Luke','Hawaii',                      ubicado_en (ubicacion('Sierra Leone',672153203)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Igor','Vermont',                     ubicado_en (ubicacion('Togo',46091507)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Allegra','New York',                 ubicado_en (ubicacion('Uzbekistan',154300529)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Rogan','North Dakota',               ubicado_en (ubicacion('United States Minor Outlying Islands',161551672)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Myles','Maine',                      ubicado_en (ubicacion('Macedonia',488648612)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Akeem','South Carolina',             ubicado_en (ubicacion('Bouvet Island',978123414)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Megan','Wyoming',                    ubicado_en (ubicacion('Hungary',675176972)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Mari','Arizona',                     ubicado_en (ubicacion('Samoa',598083302)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Price','Oregon',                     ubicado_en (ubicacion('Bhutan',488527143)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Zeph','Arizona',                     ubicado_en (ubicacion('Colombia',299697964)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Helen','Massachusetts',              ubicado_en (ubicacion('Liechtenstein',347873998)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Laurel','Pennsylvania',              ubicado_en (ubicacion('Mozambique',731603452)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Alvin','Florida',                    ubicado_en (ubicacion('Mexico',755611112)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Allen','Delaware',                   ubicado_en (ubicacion('Costa Rica',554030024)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Reed','Virginia',                    ubicado_en (ubicacion('Angola',942025384)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tobias','Kentucky',                  ubicado_en (ubicacion('Barbados',129033183)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Orson','California',                 ubicado_en (ubicacion('San Marino',689862219)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Levi','Kentucky',                    ubicado_en (ubicacion('Germany',462214810)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Florence','Maryland',                ubicado_en (ubicacion('Niue',132456246)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ina','Washington',                   ubicado_en (ubicacion('Bangladesh',629684128)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Galena','Maryland',                  ubicado_en (ubicacion('Trinidad and Tobago',173390183)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Martina','Alaska',                   ubicado_en (ubicacion('Uruguay',220424312)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Arsenio','Missouri',                 ubicado_en (ubicacion('Haiti',384820665)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Keane','Nevada',                     ubicado_en (ubicacion('Cambodia',18727994)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Avye','North Dakota',                ubicado_en (ubicacion('Monaco',330111461)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Dieter','New Jersey',                ubicado_en (ubicacion('Falkland Islands (Malvinas)',689909573)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Paula','Colorado',                   ubicado_en (ubicacion('Iceland',752184876)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Kasper','New Hampshire',             ubicado_en (ubicacion('Burkina Faso',901763737)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Aaron','Kentucky',                   ubicado_en (ubicacion('Netherlands',595457101)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ruby','Nebraska',                    ubicado_en (ubicacion('Gabon',258943615)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Nomlanga','South Carolina',          ubicado_en (ubicacion('Saint Pierre and Miquelon',651361228)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tobias','Kansas',                    ubicado_en (ubicacion('Saint Vincent and The Grenadines',392127424)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ima','District of Columbia',         ubicado_en (ubicacion('Bahrain',900908583)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Miranda','Alaska',                   ubicado_en (ubicacion('New Zealand',79706495)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Griffith','Wisconsin',               ubicado_en (ubicacion('Maldives',28176417)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ray','Maine',                        ubicado_en (ubicacion('Canada',966699259)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Shaine','Pennsylvania',              ubicado_en (ubicacion('Guinea-bissau',664088049)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Audrey','Wisconsin',                 ubicado_en (ubicacion('Hungary',407852095)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Cassady','Rhode Island',             ubicado_en (ubicacion('Djibouti',811074717)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Chase','Hawaii',                     ubicado_en (ubicacion('Cayman Islands',435335891)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Athena','Tennessee',                 ubicado_en (ubicacion('Portugal',913090945)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Bruce','California',                 ubicado_en (ubicacion('Cyprus',866918080)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Sylvia','Montana',                   ubicado_en (ubicacion('Solomon Islands',373602272)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Yael','Georgia',                     ubicado_en (ubicacion('Israel',696234097)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Adele','Delaware',                   ubicado_en (ubicacion('Trinidad and Tobago',554121643)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Felicia','Pennsylvania',             ubicado_en (ubicacion('China',363526587)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Randall','Wisconsin',                ubicado_en (ubicacion('Mexico',242114942)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ainsley','North Carolina',           ubicado_en (ubicacion('Sweden',141007501)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Francesca','Alaska',                 ubicado_en (ubicacion('Maldives',819215698)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Fiona','Maryland',                   ubicado_en (ubicacion('Saint Pierre and Miquelon',301999414)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Cheryl','Rhode Island',              ubicado_en (ubicacion('Mongolia',724052406)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Glenna','Texas',                     ubicado_en (ubicacion('Czech Republic',466996802)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Wyoming','Mississippi',              ubicado_en (ubicacion('Grenada',435521600)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Kimberly','Utah',                    ubicado_en (ubicacion('Azerbaijan',892613936)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Brian','Massachusetts',              ubicado_en (ubicacion('Guinea',901484397)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('May','Alabama',                      ubicado_en (ubicacion('Thailand',901799317)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Abbot','Connecticut',                ubicado_en (ubicacion('Switzerland',336715309)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Octavius','Rhode Island',            ubicado_en (ubicacion('Northern Mariana Islands',249373939)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Rhonda','Montana',                   ubicado_en (ubicacion('Uzbekistan',343248384)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Patience','Ohio',                    ubicado_en (ubicacion('Martinique',333182870)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Nolan','California',                 ubicado_en (ubicacion('Zimbabwe',736921715)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Maisie','Arkansas',                  ubicado_en (ubicacion('Morocco',464863851)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tashya','Iowa',                      ubicado_en (ubicacion('Macedonia',560581596)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Abel','Louisiana',                   ubicado_en (ubicacion('Puerto Rico',628855630)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Callie','Idaho',                     ubicado_en (ubicacion('Slovenia',6028146)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Perry','Alabama',                    ubicado_en (ubicacion('Saint Lucia',444093442)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Emmanuel','Iowa',                    ubicado_en (ubicacion('Sao Tome and Principe',184300666)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Cheryl','Arizona',                   ubicado_en (ubicacion('Belarus',694862898)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Kessie','Alabama',                   ubicado_en (ubicacion('Macedonia',104693608)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Benjamin','North Carolina',          ubicado_en (ubicacion('Canada',226019148)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Xanthus','Vermont',                  ubicado_en (ubicacion('Maldives',220162955)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Jonah','Nevada',                     ubicado_en (ubicacion('Philippines',663220892)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Russell','Idaho',                    ubicado_en (ubicacion('Netherlands Antilles',410000137)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Xenos','Delaware',                   ubicado_en (ubicacion('Nigeria',524016467)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Graiden','Florida',                  ubicado_en (ubicacion('Viet Nam',26553385)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Dillon','Michigan',                  ubicado_en (ubicacion('Eritrea',835558379)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Macaulay','Minnesota',               ubicado_en (ubicacion('Honduras',101637835)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Cyrus','Connecticut',                ubicado_en (ubicacion('Nepal',918394966)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Serena','Wisconsin',                 ubicado_en (ubicacion('Guadeloupe',698048822)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Quentin','New Hampshire',            ubicado_en (ubicacion('Faroe Islands',392033614)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Cynthia','Idaho',                    ubicado_en (ubicacion('Croatia',398455032)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ginger','South Carolina',            ubicado_en (ubicacion('United States',711345706)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Violet','Texas',                     ubicado_en (ubicacion('United States Minor Outlying Islands',829609557)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Stuart','Louisiana',                 ubicado_en (ubicacion('India',297892275)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Janna','Mississippi',                ubicado_en (ubicacion('Cyprus',118694106)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Lacota','Florida',                   ubicado_en (ubicacion('British Indian Ocean Territory',994703466)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Baxter','Oklahoma',                  ubicado_en (ubicacion('Honduras',58068439)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Steven','West Virginia',             ubicado_en (ubicacion('Libyan Arab Jamahiriya',337152472)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ian','Wisconsin',                    ubicado_en (ubicacion('Palestinian Territory, Occupied',496295847)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Micah','Indiana',                    ubicado_en (ubicacion('Myanmar',926584211)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Charles','Delaware',                 ubicado_en (ubicacion('Kiribati',616242488)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Idona','Texas',                      ubicado_en (ubicacion('Venezuela',986552209)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Alvin','Oregon',                     ubicado_en (ubicacion('Brazil',892588733)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Giselle','Iowa',                     ubicado_en (ubicacion('Syrian Arab Republic',248568841)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tiger','Connecticut',                ubicado_en (ubicacion('Andorra',486354004)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Thor','New Hampshire',               ubicado_en (ubicacion('Rwanda',876939874)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Baker','Massachusetts',              ubicado_en (ubicacion('Vanuatu',417899059)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Elijah','Kansas',                    ubicado_en (ubicacion('Grenada',596633584)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Wyoming','Kansas',                   ubicado_en (ubicacion('Liberia',359865273)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Adena','Kentucky',                   ubicado_en (ubicacion('French Polynesia',756916795)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Chantale','Tennessee',               ubicado_en (ubicacion('Burundi',568412963)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Helen','Rhode Island',               ubicado_en (ubicacion('Romania',255907939)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Silas','Kansas',                     ubicado_en (ubicacion('Yemen',36761734)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Gisela','Hawaii',                    ubicado_en (ubicacion('Morocco',610738095)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Rooney','Colorado',                  ubicado_en (ubicacion('New Caledonia',941054541)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Porter','Tennessee',                 ubicado_en (ubicacion('Honduras',281875130)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Uriel','Virginia',                   ubicado_en (ubicacion('Bulgaria',611889434)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Lynn','Virginia',                    ubicado_en (ubicacion('Sudan',571691247)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Jeanette','Connecticut',             ubicado_en (ubicacion('Netherlands',784817180)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Rana','Kentucky',                    ubicado_en (ubicacion('France',832586367)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Macy','Oklahoma',                    ubicado_en (ubicacion('Pakistan',209435529)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('George','Vermont',                   ubicado_en (ubicacion('Seychelles',387473886)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Sara','Colorado',                    ubicado_en (ubicacion('Saint Helena',576352977)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Naida','South Dakota',               ubicado_en (ubicacion('Timor-leste',380487798)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Keiko','Louisiana',                  ubicado_en (ubicacion('Slovenia',525419792)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Mason','Tennessee',                  ubicado_en (ubicacion('Saint Lucia',787161850)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Zelda','New Jersey',                 ubicado_en (ubicacion('Saint Pierre and Miquelon',954666645)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Kyle','California',                  ubicado_en (ubicacion('Tuvalu',832632943)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tiger','Alaska',                     ubicado_en (ubicacion('Australia',560243522)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Chelsea','Arkansas',                 ubicado_en (ubicacion('Malta',403723855)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Edward','District of Columbia',      ubicado_en (ubicacion('Viet Nam',125685600)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Tiger','Maryland',                   ubicado_en (ubicacion('Japan',729315903)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Renee','Pennsylvania',               ubicado_en (ubicacion('Dominican Republic',67311579)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Wade','North Carolina',              ubicado_en (ubicacion('Tunisia',616941104)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Rhiannon','Montana',                 ubicado_en (ubicacion('Montserrat',827731194)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Dominic','Delaware',                 ubicado_en (ubicacion('Cocos (Keeling) Islands',519118938)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Knox','Oklahoma',                    ubicado_en (ubicacion('Lebanon',329096016)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Burton','Nebraska',                  ubicado_en (ubicacion('American Samoa',309806165)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Hoyt','New Jersey',                  ubicado_en (ubicacion('Brunei Darussalam',595714341)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Yoshi','California',                 ubicado_en (ubicacion('South Africa',775237560)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Cailin','Arizona',                   ubicado_en (ubicacion('Jamaica',948741559)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Colette','Colorado',                 ubicado_en (ubicacion('Palestinian Territory, Occupied',503151672)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Latifah','Arkansas',                 ubicado_en (ubicacion('Indonesia',287917194)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Dolan','South Carolina',             ubicado_en (ubicacion('Iceland',658984310)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Zeus','Washington',                  ubicado_en (ubicacion('Kyrgyzstan',355384718)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Jordan','California',                ubicado_en (ubicacion('Netherlands Antilles',938488476)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Yeo','Virginia',                     ubicado_en (ubicacion('Gibraltar',571530764)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Herrod','Indiana',                   ubicado_en (ubicacion('Madagascar',692491231)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Aquila','Arkansas',                  ubicado_en (ubicacion('Austria',549859432)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Marny','Delaware',                   ubicado_en (ubicacion('Niue',878424202)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Dennis','Connecticut',               ubicado_en (ubicacion('Macao',660956173)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Francis','Virginia',                 ubicado_en (ubicacion('Egypt',364351177)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Hanna','Wyoming',                    ubicado_en (ubicacion('Botswana',779752575)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Brennan','Virginia',                 ubicado_en (ubicacion('Cameroon',94630285)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Amela','Alaska',                     ubicado_en (ubicacion('Sierra Leone',197876283)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Logan','Virginia',                   ubicado_en (ubicacion('Chad',525507813)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Demetria','Iowa',                    ubicado_en (ubicacion('Brazil',578731708)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Byron','Arizona',                    ubicado_en (ubicacion('Greenland',912506400)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Jakeem','Nevada',                    ubicado_en (ubicacion('Mozambique',986898027)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Price','Vermont',                    ubicado_en (ubicacion('United Arab Emirates',896416353)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Liberty','Minnesota',                ubicado_en (ubicacion('Austria',675726098)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Vivien','Pennsylvania',              ubicado_en (ubicacion('Jordan',281365468)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Jelani','Nevada',                    ubicado_en (ubicacion('American Samoa',610647917)));
INSERT INTO direccion (dir_nombre,dir_estado,dir_pais ) VALUES ('Ruby','New Hampshire',               ubicado_en (ubicacion('Uruguay',725705854)));
